#!/bin/bash
#
# Concatenate a list of PDF files. Requires ghostscript.
# Usage: catdpf output_file input_file1 input_file2 ...

if [ $# -ne 2 ]; then
  echo "Usage: catdpf output_file input_file1 input_file2 ..."; exit 1
fi

gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile="$1" "$@"